name: Build React Webpage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cancel:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: cancel
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.17.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      
      - name: Install dependencies
        run: npm install    
      
      - name: Generate build
        run: npm run build

      - name: Share build artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: build
          if-no-files-found: error
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: build
      
      - name: Push to build dir on master branch
        run: |
          mv build/ docs/
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add docs
          git commit -am "Automated React Build for Deploy"
          git push
