name: Build React Webpage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'push' }}
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: cancel
    env:
      REACT_APP_PROJECTS_URL: ${{ secrets.REACT_APP_PROJECTS_URL }}
      REACT_APP_ABOUT_URL: ${{ secrets.REACT_APP_ABOUT_URL }}
      REACT_APP_SKILLS_URL: ${{ secrets.REACT_APP_SKILLS_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - name: Install dependencies
        run: npm install

      - name: List files
        run: ls -la

      - name: Generate build
        run: npm run build

      - name: Share build artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: build
          if-no-files-found: error

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: List files
        run: ls -la

      - name: Setup Git
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: build

      - name: Commit Build
        run: |
          rm -rf docs
          mv build docs
          git add docs
          git commit --allow-empty -am "Automated React Build for Deploy"
          git push -u origin gh-pages

  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: build

      - name: List files
        run: ls -la

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --exclude '.git/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ${{ secrets.SOURCE_DIR }}
